# Welcome to the sample config file
# Below you will find various config sections and options
# Default values are shown

# The string to prefix bot commands with
command_prefix: "!"

# Options for connecting to the bot's Matrix account
matrix:
  # The Matrix User ID of the bot account
  user_id: "@bot:example.com"
  # Matrix account password
  user_password: ""
  # The public URL at which the homeserver's Client-Server API can be accessed
  homeserver_url: https://example.com
  # The device ID that is a **non pre-existing** device
  # If this device ID already exists, messages will be dropped silently in
  # encrypted rooms
  device_id: DRAWING
  # What to name the logged in device
  device_name: Drawing Challenge Bot

storage:
  # The database connection string
  # For SQLite3, this would look like:
  #     database: "sqlite://bot.db"
  # For Postgres, this would look like:
  #     database: "postgres://username:password@localhost/dbname?sslmode=disable"
  #database: "postgres://drawing-challenge-bot:remindme@localhost/drawing-challenge-bot?sslmode=disable"
  database: "sqlite://bot.db"
  # The path to a directory for internal bot storage
  # containing encryption keys, sync tokens, etc.
  store_path: "./store"

reddit:
  # Reddit API settings
  client_id: your_client_id
  client_secret: your_client_secret
  user_agent: "drawing-challenge-bot"

# Logging setup
logging:
  # Logging level
  # Allowed levels are 'INFO', 'WARNING', 'ERROR', 'DEBUG' where DEBUG is most verbose
  level: INFO
  # Configure logging to a file
  file_logging:
    # Whether logging to a file is enabled
    enabled: false
    # The path to the file to log to. May be relative or absolute
    filepath: bot.log
  # Configure logging to the console (stdout/stderr)
  console_logging:
    # Whether console logging is enabled
    enabled: true
